--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PJZ9n/ResourcePackTools
build-by-default: true
branches:
  - master
projects:
  ResourcePackTools:
    type: library
    model: virion
  ResourcePackToolsPlugin: []
...
