--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PJZ9n/ResourcePackTools
build-by-default: true
branches:
  - master
projects:
  ResourcePackTools:
    path: resourcepacktools/
    type: library
    model: virion
  ResourcePackToolsPlugin:
    path: resourcepacktools/
    icon: /icon.png
  ResourceExample:
    path: examples/resourceexample/
    libs:
      - src: pjz9n/resourcepacktools/ResourcePackTools
        version: 2.0.0
...
