name: ResourceExample
version: 1.0.0
main: pjz9n\resourceexample\Main
api: 4.0.0
commands:
  resourceexample:
    description: Manage ResourcePack
    permission: resourceexample.command.resourceexample
permissions:
  resourceexample.command.resourceexample:
    default: true
