name: ResourcePackToolsPlugin
version: 2.1.0
main: pjz9n\resourcepacktools\Main
api: 3.0.0
commands:
  resourcepack:
    description: Manage ResourcePack
    usage: "/resourcepack register <filename>\n
    /resourcepack unregisterbyindex <index>\n
    /resourcepack unregisterbyuuid <uuid>\n
    /resourcepack list pack:uuid"
    aliases:
      - rp
    permission: resourcepacktools.command.resourcepack
permissions:
  resourcepacktools.command.resourcepack:
    default: op
