name: ResourcePackToolsPlugin
version: 2.2.0
main: pjz9n\resourcepacktools\Main
api: 4.0.0
commands:
  resourcepack:
    description: Manage ResourcePack
    usage: "/resourcepack register(r) <filename>\n
    /resourcepack unregisterbyindex(urbi) <index>\n
    /resourcepack unregisterbyuuid(urbu) <uuid>\n
    /resourcepack list(l) pack(p):uuid(u)"
    aliases:
      - rp
    permission: resourcepacktools.command.resourcepack
permissions:
  resourcepacktools.command.resourcepack:
    default: op
